/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoopPool;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.SequenceInputStream;
import java.util.Vector;
import javax.sound.sampled.AudioFileFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kamonson17 And Timothy
 */
class MyCustomFilter extends javax.swing.filechooser.FileFilter {

    @Override
    public boolean accept(File file) {
        // Allow only directories, or files with ".txt" extension
        return file.isDirectory() || file.getAbsolutePath().endsWith(".wav");
    }

    @Override
    public String getDescription() {
        // This description will be displayed in the dialog,
        // hard-coded = ugly, should be done via I18N
        return "Text documents (*.wav)";
    }
}

public class LoopPoolGUI extends javax.swing.JFrame {

    /**
     * Creates new form LoopPoolGUI
     */
    AudioFile a = new AudioFile();
    Boolean b = true;
    Vector<AudioFile> v = new Vector();

    public LoopPoolGUI() {
        initComponents();
    }

    public void addItem(AudioFile S) {
        if (this.jPanel1.isShowing()) {
            DefaultTableModel model = (DefaultTableModel) this.MusicTable.getModel();
            model.addRow(new Object[]{S});
        } else if (this.jPanel2.isShowing()) {
            DefaultTableModel model = (DefaultTableModel) this.MusicTable2.getModel();
            model.addRow(new Object[]{S});
        }
    }

    void Stop() {
        for (int i = 0; i < v.size(); i++) {
            v.get(i).AudioStop();
        }

    }

    void Play() {
        if (MusicTable.getSelectedRow() >= 0 && MusicTable2.getSelectedRow() < 0) {
            v.get(this.MusicTable.convertRowIndexToModel(
                    this.MusicTable.getSelectedRow())).AudioPlay();
        }
        if (MusicTable.getSelectedRow() >= 0 && MusicTable2.getSelectedRow() >= 0) {
            v.get(this.MusicTable.convertRowIndexToModel(
                    this.MusicTable.getSelectedRow())).AudioPlay();
            v.get(this.MusicTable2.convertRowIndexToModel(
                    this.MusicTable2.getSelectedRow())).AudioPlay();
        }
        if (MusicTable.getSelectedRow() < 0 && MusicTable2.getSelectedRow() >= 0) {
            v.get(this.MusicTable2.convertRowIndexToModel(
                    this.MusicTable2.getSelectedRow())).AudioPlay();
        }
    }

    public void ClearRow(int r, javax.swing.JTable t) {
        DefaultTableModel model = (DefaultTableModel) t.getModel();
        {
            model.removeRow(r);
        }
    }

    void importFile() {
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            //this.a.setName(fileChooser.getName(file));
            v.add(new AudioFile(file.getAbsolutePath()));
            addItem(v.get(v.size() - 1));

        } else {
            System.out.println("File access cancelled by user.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        PlayB = new javax.swing.JButton();
        RecordB = new javax.swing.JButton();
        ExportB = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MusicTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MusicTable2 = new javax.swing.JTable();
        StopB = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Open = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PlayB.setText("Play");
        PlayB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayBActionPerformed(evt);
            }
        });
        PlayB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PlayBKeyTyped(evt);
            }
        });

        RecordB.setText("Record");

        ExportB.setText("Export");
        ExportB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportBActionPerformed(evt);
            }
        });

        jButton4.setText("Chang Start Time");

        MusicTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        MusicTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MusicTableKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MusicTableKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MusicTableKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(MusicTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Layer 1", jPanel1);

        MusicTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        MusicTable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MusicTable2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MusicTable2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MusicTable2KeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(MusicTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Layer 2", jPanel2);

        StopB.setText("Stop");
        StopB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopBActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        Open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        Open.setText("Open Audio File");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });
        jMenu1.add(Open);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PlayB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RecordB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExportB, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StopB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlayB)
                    .addComponent(RecordB)
                    .addComponent(ExportB)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(StopB))
                .addGap(29, 29, 29)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        importFile();
        // jTextField1.setText(a.sLength());
    }//GEN-LAST:event_OpenActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void StopBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopBActionPerformed
        Stop();
    }//GEN-LAST:event_StopBActionPerformed

    private void PlayBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayBActionPerformed
        Play();
    }//GEN-LAST:event_PlayBActionPerformed

    private void ExportBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportBActionPerformed
        try {
            // for (int i = 0; i < v.size() - 1; i++) {
//                AudioInputStream clip1 = AudioSystem.getAudioInputStream(new File(v.get(i).getLocation()));
//                AudioInputStream clip2 = AudioSystem.getAudioInputStream(new File(v.get(i + 1).getLocation()));
            AudioInputStream clip1 = AudioSystem.getAudioInputStream(new File(v.get(this.MusicTable.convertRowIndexToModel(this.MusicTable.getSelectedRow())).getLocation()));
            AudioInputStream clip2 = AudioSystem.getAudioInputStream(new File(v.get(this.MusicTable.convertRowIndexToModel(this.MusicTable.getSelectedRow())).getLocation()));
            AudioInputStream appendedFiles
                    = new AudioInputStream(
                            new SequenceInputStream(clip1, clip2),
                            clip1.getFormat(),
                            clip1.getFrameLength() + clip2.getFrameLength());
            AudioSystem.write(appendedFiles, AudioFileFormat.Type.WAVE, new File("C:\\Users\\kamonson17\\Desktop\\newwav.wav"));

        } catch (Exception Ex) {
            Ex.printStackTrace();
        }
    }//GEN-LAST:event_ExportBActionPerformed

    private void PlayBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PlayBKeyTyped
        Play();
    }//GEN-LAST:event_PlayBKeyTyped

    private void MusicTableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MusicTableKeyTyped
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_DELETE) {
            this.ClearRow(this.MusicTable.getSelectedRow(), this.MusicTable);
        }
    }//GEN-LAST:event_MusicTableKeyTyped

    private void MusicTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MusicTableKeyReleased
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_SPACE) {
            Stop();
            b = true;
        }
    }//GEN-LAST:event_MusicTableKeyReleased

    private void MusicTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MusicTableKeyPressed
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_SPACE) {
            if (b) {
                b = false;
                Play();
            }
        }
    }//GEN-LAST:event_MusicTableKeyPressed

    private void MusicTable2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MusicTable2KeyPressed
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_DELETE) {
            this.ClearRow(this.MusicTable2.getSelectedRow(), this.MusicTable2);
        }
    }//GEN-LAST:event_MusicTable2KeyPressed

    private void MusicTable2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MusicTable2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_MusicTable2KeyReleased

    private void MusicTable2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MusicTable2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_MusicTable2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoopPoolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoopPoolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoopPoolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoopPoolGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoopPoolGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Exit;
    private javax.swing.JButton ExportB;
    private javax.swing.JTable MusicTable;
    private javax.swing.JTable MusicTable2;
    private javax.swing.JMenuItem Open;
    private javax.swing.JButton PlayB;
    private javax.swing.JButton RecordB;
    private javax.swing.JButton StopB;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
